### PR TITLE
Updating the site with new events (and newer middleman version)

### PR DESCRIPTION
**Pull request by ilonashub**

### CODE REVIEW

**Comment by abonas** [comment]
I would suggest doing the middleman change and all the updates to the gem versions in a separate request and not with the events update. they are unrelated, and it will be easier to review each on its own.

**Comment by ilonashub** [comment]
OK, I'll send 2 different requests

**Comment by abonas** [comment]
@ilonashub btw I see here above there are 2 pr one named "using older version of middleman" and the other one "new middleman" :) - can you perhaps explain? maybe those 2 can be unified? (maybe not, I was just trying to understand both of them)

**Comment by ilonashub** [comment]
Yeah I can see the cunfusion :)
In the first commit I updates with the newst middleman version - and everything worked BUT the foundation template didn't worked correctly - which then got me to change the middleman version to a bit older one, so that the css will work.

**Pull request closed without merging**
